---  
- name: disable selinux part one
  blockinfile:
    dest: /etc/selinux/config
    insertafter: SELINUX=enforcing
    content: SELINUX=disabled

- name: disable selinux part two
  blockinfile:
    dest: /etc/selinux/config
    marker: SELINUX=enforcing
    content: ""

- name: Setup loop script
  blockinfile:
    dest: "{{ loop_script_destination }}"
    create: yes
    owner: root
    group: root
    mode: "a+x"
    content: |
      #!/bin/sh
      sleep {{ loop_sleep_time }}
      while :
      do result=$(ps -ef | grep -v grep | grep /usr/lib/vmware/view/bin/vmware-view)
      if [ -z "$result" ]; then
      reboot
      fi
      sleep {{ loop_refresh_time }}
      done

- name: Setup viewloop.service
  blockinfile:
    dest: "{{ viewloop_service_destination }}"
    create: yes
    content: |
      [Unit]
      Description="Starts VMware loop.sh script on login"

      [Service]
      ExecStart=/bin/sh /loop.sh

      [Install]
      WantedBy=multi-user.target

- name: Make autostart directory
  file: path=/home/{{ local_username }}/.config/autostart state=directory

- name: Setup viewclient.desktop
  blockinfile:
    dest: /home/{{ local_username }}/.config/autostart/viewclient.desktop
    create: yes
    content: |
      [Desktop Entry]
      Version=1.0
      Name=viewclient
      Comment=Starts VMware Horizon View client
      Exec=/bin/sh -c "sleep {{ client_load_delay }} && vmware-view '--nonInteractive' '--serverURL={{ client_server_url }}' --desktopName='{{ client_desktop_name }}' '--nomenubar' '--once' '--allmonitors'"
      Terminal=false
      Type=Application
      Icon=vmware-view
      Categories=network
      StartupNotify=false

- name: enable viewloop.service
  shell: systemctl enable viewloop.service
  args:
    executable: /bin/bash

- name: enable autologin for local user account, disable Wayland for H.264 decode
  blockinfile:
    dest: /etc/gdm/custom.conf
    insertafter: '\[daemon\]'
    content: |
      AutomaticLoginEnable=true
      AutomaticLogin={{ local_username }}
      WaylandEnable=false

- name: configure ctrl alt delete
  blockinfile:
    dest: /etc/vmware/view-mandatory-config
    create: yes
    content: view.sendCtrlAltDelToLocal = TRUE

- name: disable lock screen, super key, overlay key and desktop notifications
  shell: sudo -u {{ local_username }} DISPLAY=:0 gsettings set org.gnome.desktop.screensaver lock-enabled false && sudo -u {{ local_username }} DISPLAY=:0 gsettings set org.gnome.mutter overlay-key '' && sudo -u {{ local_username }} DISPLAY=:0 gsettings set org.gnome.desktop.session idle-delay 0 && sudo -u {{ local_username }} DISPLAY=:0 gsettings set org.gnome.desktop.notifications show-banners false
  args:
    executable: /bin/bash